#!/usr/bin/bash

sudo pacman-key --recv-keys 313F5ABD
sudo pacman-key --lsign-key 313F5ABD

CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD_CYAN='\033[1;36m'

echo -e "${BOLD_CYAN}Updating system\n${NC}"
sudo pacman -Syu --noprogressbar --noconfirm --color always
sudo pacman -S base-devel --noconfirm --noprogressbar
cd ~

# Install vim and sed
echo -e "${BOLD_CYAN}Installing vim, sed, and git\n${NC}"
sudo pacman -Syu --noprogressbar --noconfirm --color always vim sed git

# Make directory used for setup
echo -e "\n${BOLD_CYAN}Making new directory '/home/$USER/.fsetup'${NC}"
mkdir ~/.fsetup
cd ~/.fsetup

# Configure for dual booting
# Install os-prober
echo -e "\n${BOLD_CYAN}Installing os-prober${NC}"
sudo pacman -S --needed --noprogressbar os-prober
# Enable os prober
echo -e "${BOLD_CYAN}Enabling os-prober\n${NC}"
sudo sed -i.bak "s/^GRUB_DISABLE_OS_PROBER=.*/GRUB_DISABLE_OS_PROBER=true/" /etc/default/grub

# Install Kernel 5.15.rc3-1, needed to fix audio and wifi issues
# Getting it from miffe so that compiling is not needed.
echo -e "\n${BOLD_CYAN}Downloading kernel 5.15.rc3 from http://arch.miffe.org/x86_64/linux-mainline-5.15rc3-1-x86_64.pkg.tar.zst${NC}"
wget http://arch.miffe.org/x86_64/linux-mainline-5.15rc3-1-x86_64.pkg.tar.zst -o ~/.fsetup
cd ~/.fsetup
echo -e "\n${BOLD_CYAN}Installing... This will take a while...\n${NC}"
sudo pacman -U linux-mainline-5.15rc3-1-x86_64.pkg.tar.zst

# Refresh Grub
echo -e "\n${BOLD_CYAN}Refreshing grub...\n${NC}"
sudo grub-mkconfig -o /boot/grub/grub.cfg

# Ask to reboot
echo -e "${BOLD_CYAN}The computer needs to reboot to apply kernel changes.${NC}"
echo -e "${BOLD_CYAN}Rebooting in 5 seconds...${NC}"
sleep 5
sudo reboot now
