#!/usr/bin/bash

CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD_CYAN='\033[1;36m'

sudo pacman -Syu bluez
sudo pacman -Syu bluez-utils
sudo systemctl enable bluetooth.service
sudo pacman -Syu bluedevil

yay -S touchegg
yay -S touche
cp -rf ./touchegg.conf ~/.config/touchegg/

sudo rm -rf ~/.fsetup